2023-12-24 15:21:18,687 server listening on 127.0.0.1:8765
2023-12-24 15:21:18,687 server listening on [::1]:8765
2023-12-24 15:21:26,864 connection open
2023-12-24 15:21:37,092 exchange 8 PLN
2023-12-24 15:21:37,093 ['exchange', '8', 'PLN']
2023-12-24 15:21:37,368 {"16.12.2023": [{"EUR": {"buy": 40.0, "sale": 41.0}}, {"PLN": {"buy": 9.376, "sale": 9.376}}, {"USD": {"buy": 36.95, "sale": 37.45}}]}
2023-12-24 15:21:37,368 connection closed
2023-12-24 15:21:37,397 connection open
2023-12-24 15:22:10,292 egdf
2023-12-24 15:22:10,292 ['egdf']
2023-12-24 15:22:10,512 {"24.12.2023": [{"EUR": {"buy": 40.8, "sale": 41.8}}, {"USD": {"buy": 37.3, "sale": 37.8}}]}
2023-12-24 15:22:10,512 connection closed
2023-12-24 15:22:10,512 connection open
2023-12-24 15:22:21,163 exit
2023-12-24 15:22:21,163 ['exit']
2023-12-24 15:22:21,340 {"24.12.2023": [{"EUR": {"buy": 40.8, "sale": 41.8}}, {"USD": {"buy": 37.3, "sale": 37.8}}]}
2023-12-24 15:22:21,340 connection handler failed
Traceback (most recent call last):
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "d:\Projects\Repositories\HomeworkWeb05\server.py", line 96, in open_websocket
    await websocket.send(return_data)
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2023-12-24 15:22:21,340 connection closed
2023-12-24 15:22:59,075 connection open
2023-12-24 15:23:00,921 sgfd
2023-12-24 15:23:00,921 ['sgfd']
2023-12-24 15:23:01,155 {"24.12.2023": [{"EUR": {"buy": 40.8, "sale": 41.8}}, {"USD": {"buy": 37.3, "sale": 37.8}}]}
2023-12-24 15:23:01,171 connection closed
2023-12-24 15:23:01,192 connection open
2023-12-24 15:23:37,357 exit
2023-12-24 15:23:37,357 ['exit']
2023-12-24 15:23:37,543 {"24.12.2023": [{"EUR": {"buy": 40.8, "sale": 41.8}}, {"USD": {"buy": 37.3, "sale": 37.8}}]}
2023-12-24 15:23:37,543 connection handler failed
Traceback (most recent call last):
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "d:\Projects\Repositories\HomeworkWeb05\server.py", line 96, in open_websocket
    await websocket.send(return_data)
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2023-12-24 15:23:37,543 connection closed
2023-12-24 15:23:46,178 connection open
2023-12-24 15:23:54,081 exchange 8 PLN
2023-12-24 15:23:54,081 ['exchange', '8', 'PLN']
2023-12-24 15:23:54,267 {"16.12.2023": [{"EUR": {"buy": 40.0, "sale": 41.0}}, {"PLN": {"buy": 9.376, "sale": 9.376}}, {"USD": {"buy": 36.95, "sale": 37.45}}]}
2023-12-24 15:23:54,267 connection closed
2023-12-24 15:23:54,288 connection open
2023-12-24 15:24:12,474 exit
2023-12-24 15:24:12,474 ['exit']
2023-12-24 15:24:12,675 {"24.12.2023": [{"EUR": {"buy": 40.8, "sale": 41.8}}, {"USD": {"buy": 37.3, "sale": 37.8}}]}
2023-12-24 15:24:12,676 connection handler failed
Traceback (most recent call last):
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "d:\Projects\Repositories\HomeworkWeb05\server.py", line 96, in open_websocket
    await websocket.send(return_data)
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "C:\Users\파ster\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2023-12-24 15:24:12,676 connection closed
2023-12-24 15:24:34,091 Server is stopped.
2023-12-24 15:24:34,091 server closing
2023-12-24 15:24:34,091 server closed
